spring.datasource.url=jdbc:mysql://localhost:3306/inventa?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8080
jwt.secret=inventa-clave-super-secreta-2024
jwt.expiration=86400000